CPP = g++ -Wall -Werror -Wextra -g

all : pretty encode evel

pretty : pretty.cpp icfp.hpp
	$(CPP) -o '$@' '$<'

encode : encode.cpp icfp.hpp
	$(CPP) -o '$@' '$<'

evel : evel.cpp icfp.hpp
	$(CPP) -o '$@' '$<'
